# -*- coding: utf-8 -*-
"""temparature.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AdUgwh8kRYTsrAt48G3yQQPMl2QvMAhT
"""

# Uploading all the temperature CSV files
from google.colab import files
uploaded = files.upload()

# Loading and combining the uploaded CSV files
import pandas as pd
from io import StringIO

dataframes = []
for filename in uploaded.keys():
    content = uploaded[filename].decode('utf-8')
    df = pd.read_csv(StringIO(content))
    dataframes.append(df)

data = pd.concat(dataframes, ignore_index=True)

# Defining months and seasons
months = ["January", "February", "March", "April", "May", "June",
          "July", "August", "September", "October", "November", "December"]

seasons = {
    "Summer": ["December", "January", "February"],
    "Autumn": ["March", "April", "May"],
    "Winter": ["June", "July", "August"],
    "Spring": ["September", "October", "November"]
}

# Calculating average temperature per season
season_results = []
for season, season_months in seasons.items():
    avg_temp = data[season_months].mean().mean()
    season_results.append(f"{season}: {avg_temp:.2f} °C")

with open("average_temp.txt", "w") as f:
    f.write("\n".join(season_results))

# Finding station(s) with largest temperature range
station_groups = data.groupby("STATION_NAME")[months]
temp_range = station_groups.max().max(axis=1) - station_groups.min().min(axis=1)
max_range = temp_range.max()
stations_with_max_range = temp_range[temp_range == max_range]

with open("largest_temp_range_station.txt", "w") as f:
    f.write(f"Largest Temperature Range: {max_range:.2f} °C\n")
    f.write("Station(s):\n")
    for station in stations_with_max_range.index:
        f.write(f"{station}\n")

# Finding warmest and coolest stations
avg_temp_per_station = station_groups.mean().mean(axis=1)
warmest = avg_temp_per_station[avg_temp_per_station == avg_temp_per_station.max()]
coolest = avg_temp_per_station[avg_temp_per_station == avg_temp_per_station.min()]

with open("warmest_and_coolest_station.txt", "w") as f:
    f.write(f"Warmest Average Temperature: {warmest.max():.2f} °C\n")
    f.write("Warmest Station(s):\n")
    for station in warmest.index:
        f.write(f"{station}\n")
    f.write(f"\nCoolest Average Temperature: {coolest.min():.2f} °C\n")
    f.write("Coolest Station(s):\n")
    for station in coolest.index:
        f.write(f"{station}\n")

# Downloading the result files
files.download("average_temp.txt")
files.download("largest_temp_range_station.txt")
files.download("warmest_and_coolest_station.txt")